2024-03-19 02:50:13.782940: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.782942: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.785045: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.801785: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.821277: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.821277: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.794649: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.805063: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.825716: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.826022: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.826088: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.836217: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.823633: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.835787: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.836418: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.836455: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.827163: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.831966: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.831959: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.832659: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.841580: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.841576: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.841598: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.842253: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.847557: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.850958: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.858228: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.862397: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.879152: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.879167: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.911658: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:13.911679: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 7.18GiB (7706039091 bytes) by rematerialization; only reduced to 48.50GiB (52076478480 bytes), down from 48.50GiB (52076478480 bytes) originally
2024-03-19 02:50:23.860199: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.860437: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.860554 3652957 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.865907: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.865912: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.866148: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
2024-03-19 02:50:23.866145: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.866262  246084 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


E0319 02:50:23.866262  246085 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.870395: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.870648: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.870773 2522669 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.877275: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.877530: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.877654 2522671 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
2024-03-19 02:50:23.879856: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
2024-03-19 02:50:23.880038: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


E0319 02:50:23.880127 3652955 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.897607: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.897420: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.897725: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
2024-03-19 02:50:23.897655: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.897789  246083 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
E0319 02:50:23.897750 3035447 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.900531: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.900862: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.900752: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
2024-03-19 02:50:23.900965: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.901023  246082 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
E0319 02:50:23.900888 3652956 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.903158: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.903389: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.903506 1494333 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.906367: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.906510: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.906568 2522670 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.906732: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.906950: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.907051 2522672 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.907458: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.907688: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.907938: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
E0319 02:50:23.907823 3652954 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.908042: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.908112 1494334 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.909071: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.909225: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
2024-03-19 02:50:23.909183: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.909289: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
2024-03-19 02:50:23.909273: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
E0319 02:50:23.909300 3035445 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


E0319 02:50:23.909360 3035446 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.909417: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.909472 3035448 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.910585: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.910831: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
2024-03-19 02:50:23.910909: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
E0319 02:50:23.910962 1494332 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.911155: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.911256 1494331 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.920466: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.920701: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.920856 1924033 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.922022: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.922128: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.922192 1924032 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.923210: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.923410: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.923488 1840373 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
2024-03-19 02:50:23.923502: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.923671: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.923735: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.923840 1924034 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.923851: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.923913 1924035 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
2024-03-19 02:50:23.923755: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.923990: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.924114 1840371 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.952931: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.953069: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.953144  460774 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.953360: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.953466: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.953529  460773 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.984249: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.984429: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.984488  460776 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.984641: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.984746: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.984805  460775 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.992878: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.993099: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.993174 1840370 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-19 02:50:23.993332: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-19 02:50:23.993466: W external/tsl/tsl/framework/bfc_allocator.cc:494] _*********************************************************************______________________________
E0319 02:50:23.993553 1840372 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  256.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.25GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 256.00MiB
		Entry Parameter Subshape: f64[32,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[32,1024,1024], c128[1024,1024,1024])
		==========================


srun: error: r6i6n3: tasks 1-3: Exited with exit code 1
srun: Terminating StepId=1139838.37
srun: error: r8i7n1: tasks 28,30-31: Exited with exit code 1
srun: error: r6i6n4: tasks 4-6: Exited with exit code 1
srun: error: r8i6n6: tasks 12,14-15: Exited with exit code 1
srun: error: r6i6n5: tasks 8-9,11: Exited with exit code 1
srun: error: r8i6n7: tasks 17-19: Exited with exit code 1
srun: error: r8i6n8: tasks 21-23: Exited with exit code 1
srun: error: r8i7n0: tasks 24,26-27: Exited with exit code 1
slurmstepd: error: *** STEP 1139838.37 ON r6i6n3 CANCELLED AT 2024-03-19T02:50:25 ***
srun: error: r8i7n0: task 25: Exited with exit code 1
srun: error: r8i6n7: task 16: Exited with exit code 1
srun: error: r8i7n1: task 29: Exited with exit code 1
srun: error: r6i6n5: task 10: Exited with exit code 1
srun: error: r8i6n8: task 20: Exited with exit code 1
srun: error: r6i6n3: task 0: Exited with exit code 1
srun: error: r6i6n4: task 7: Exited with exit code 1
srun: error: r8i6n6: task 13: Exited with exit code 1
