2024-03-17 15:32:06.073805: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below -41.99GiB (-45081793331 bytes) by rematerialization; only reduced to 200.00GiB (214748364816 bytes), down from 200.00GiB (214748364816 bytes) originally
2024-03-17 15:32:06.073800: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below -41.99GiB (-45081793331 bytes) by rematerialization; only reduced to 200.00GiB (214748364816 bytes), down from 200.00GiB (214748364816 bytes) originally
2024-03-17 15:32:06.089363: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below -41.99GiB (-45081793331 bytes) by rematerialization; only reduced to 200.00GiB (214748364816 bytes), down from 200.00GiB (214748364816 bytes) originally
2024-03-17 15:32:06.089867: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below -41.99GiB (-45081793331 bytes) by rematerialization; only reduced to 200.00GiB (214748364816 bytes), down from 200.00GiB (214748364816 bytes) originally
2024-03-17 15:32:06.120732: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below -41.99GiB (-45081793331 bytes) by rematerialization; only reduced to 200.00GiB (214748364816 bytes), down from 200.00GiB (214748364816 bytes) originally
2024-03-17 15:32:06.120750: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below -41.99GiB (-45081793331 bytes) by rematerialization; only reduced to 200.00GiB (214748364816 bytes), down from 200.00GiB (214748364816 bytes) originally
2024-03-17 15:32:06.121423: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below -41.99GiB (-45081793331 bytes) by rematerialization; only reduced to 200.00GiB (214748364816 bytes), down from 200.00GiB (214748364816 bytes) originally
2024-03-17 15:32:06.121445: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below -41.99GiB (-45081793331 bytes) by rematerialization; only reduced to 200.00GiB (214748364816 bytes), down from 200.00GiB (214748364816 bytes) originally
2024-03-17 15:32:16.142973: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 64.00GiB (rounded to 68719476736)requested by op 
2024-03-17 15:32:16.143130: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 64.00GiB (rounded to 68719476736)requested by op 
2024-03-17 15:32:16.143192: W external/tsl/tsl/framework/bfc_allocator.cc:494] ________________******************__________________________________________________________________
E0317 15:32:16.143302  907660 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 68719476736 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:   64.00GiB
     preallocated temp allocation:   64.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:  132.00GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 2:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: fft
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: (c64[256,2048,2048], c64[2048,2048,2048])
		==========================


2024-03-17 15:32:16.143335: W external/tsl/tsl/framework/bfc_allocator.cc:494] ________________******************__________________________________________________________________
E0317 15:32:16.143444  907661 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 68719476736 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:   64.00GiB
     preallocated temp allocation:   64.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:  132.00GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 2:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: fft
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: (c64[256,2048,2048], c64[2048,2048,2048])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 107, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 54, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 68719476736 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:   64.00GiB
     preallocated temp allocation:   64.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:  132.00GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 2:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: fft
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: (c64[256,2048,2048], c64[2048,2048,2048])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 107, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 54, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 68719476736 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:   64.00GiB
     preallocated temp allocation:   64.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:  132.00GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 2:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: fft
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: (c64[256,2048,2048], c64[2048,2048,2048])
		==========================


2024-03-17 15:32:16.157957: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 64.00GiB (rounded to 68719476736)requested by op 
2024-03-17 15:32:16.157994: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 64.00GiB (rounded to 68719476736)requested by op 
2024-03-17 15:32:16.158179: W external/tsl/tsl/framework/bfc_allocator.cc:494] ________________******************__________________________________________________________________
2024-03-17 15:32:16.158188: W external/tsl/tsl/framework/bfc_allocator.cc:494] ________________******************__________________________________________________________________
E0317 15:32:16.158241  907662 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 68719476736 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:   64.00GiB
     preallocated temp allocation:   64.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:  132.00GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 2:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: fft
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: (c64[256,2048,2048], c64[2048,2048,2048])
		==========================


E0317 15:32:16.158249  907663 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 68719476736 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:   64.00GiB
     preallocated temp allocation:   64.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:  132.00GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 2:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: fft
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: (c64[256,2048,2048], c64[2048,2048,2048])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 107, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 54, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 68719476736 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:   64.00GiB
     preallocated temp allocation:   64.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:  132.00GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 2:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: fft
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: (c64[256,2048,2048], c64[2048,2048,2048])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 107, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 54, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 68719476736 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:   64.00GiB
     preallocated temp allocation:   64.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:  132.00GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 2:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: fft
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: (c64[256,2048,2048], c64[2048,2048,2048])
		==========================


2024-03-17 15:32:16.192716: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 64.00GiB (rounded to 68719476736)requested by op 
2024-03-17 15:32:16.192832: W external/tsl/tsl/framework/bfc_allocator.cc:494] ________________******************__________________________________________________________________
E0317 15:32:16.192912 3131885 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 68719476736 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:   64.00GiB
     preallocated temp allocation:   64.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:  132.00GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 2:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: fft
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: (c64[256,2048,2048], c64[2048,2048,2048])
		==========================


2024-03-17 15:32:16.193875: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 64.00GiB (rounded to 68719476736)requested by op 
2024-03-17 15:32:16.194013: W external/tsl/tsl/framework/bfc_allocator.cc:494] ________________******************__________________________________________________________________
E0317 15:32:16.194093 3131886 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 68719476736 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:   64.00GiB
     preallocated temp allocation:   64.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:  132.00GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 2:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: fft
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: (c64[256,2048,2048], c64[2048,2048,2048])
		==========================


2024-03-17 15:32:16.194203: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 64.00GiB (rounded to 68719476736)requested by op 
2024-03-17 15:32:16.194309: W external/tsl/tsl/framework/bfc_allocator.cc:494] ________________******************__________________________________________________________________
E0317 15:32:16.194378 3131887 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 68719476736 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:   64.00GiB
     preallocated temp allocation:   64.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:  132.00GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 2:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: fft
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: (c64[256,2048,2048], c64[2048,2048,2048])
		==========================


2024-03-17 15:32:16.194942: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 64.00GiB (rounded to 68719476736)requested by op 
2024-03-17 15:32:16.195058: W external/tsl/tsl/framework/bfc_allocator.cc:494] ________________******************__________________________________________________________________
E0317 15:32:16.195123 3131884 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 68719476736 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:   64.00GiB
     preallocated temp allocation:   64.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:  132.00GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 2:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: fft
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: (c64[256,2048,2048], c64[2048,2048,2048])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 107, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 54, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 68719476736 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:   64.00GiB
     preallocated temp allocation:   64.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:  132.00GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 2:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: fft
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: (c64[256,2048,2048], c64[2048,2048,2048])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 107, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 54, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 68719476736 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:   64.00GiB
     preallocated temp allocation:   64.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:  132.00GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 2:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: fft
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: (c64[256,2048,2048], c64[2048,2048,2048])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 107, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 54, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 68719476736 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:   64.00GiB
     preallocated temp allocation:   64.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:  132.00GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 2:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: fft
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: (c64[256,2048,2048], c64[2048,2048,2048])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 107, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 54, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 68719476736 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.00GiB
              constant allocation:         0B
        maybe_live_out allocation:   64.00GiB
     preallocated temp allocation:   64.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:  132.00GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 2:
		Size: 64.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: fft
		Shape: c64[2048,2048,2048]
		==========================

	Buffer 3:
		Size: 4.00GiB
		Entry Parameter Subshape: f32[256,2048,2048]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(2048, 2048, 2048)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=41
		XLA Label: all-gather-start
		Shape: (c64[256,2048,2048], c64[2048,2048,2048])
		==========================


srun: error: r7i1n0: tasks 0-1,3: Exited with exit code 1
srun: Terminating StepId=1124578.68
srun: error: r7i6n7: tasks 4-6: Exited with exit code 1
slurmstepd: error: *** STEP 1124578.68 ON r7i1n0 CANCELLED AT 2024-03-17T15:32:17 ***
srun: error: r7i1n0: task 2: Exited with exit code 1
srun: error: r7i6n7: task 7: Exited with exit code 1
