2024-03-17 17:31:05.311881: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 6.94GiB (7451025408 bytes) by rematerialization; only reduced to 49.00GiB (52613349392 bytes), down from 49.00GiB (52613349392 bytes) originally
2024-03-17 17:31:05.312123: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 6.94GiB (7451025408 bytes) by rematerialization; only reduced to 49.00GiB (52613349392 bytes), down from 49.00GiB (52613349392 bytes) originally
2024-03-17 17:31:05.319074: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 6.94GiB (7451025408 bytes) by rematerialization; only reduced to 49.00GiB (52613349392 bytes), down from 49.00GiB (52613349392 bytes) originally
2024-03-17 17:31:05.328120: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 6.94GiB (7451025408 bytes) by rematerialization; only reduced to 49.00GiB (52613349392 bytes), down from 49.00GiB (52613349392 bytes) originally
2024-03-17 17:31:05.338636: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 6.94GiB (7451025408 bytes) by rematerialization; only reduced to 49.00GiB (52613349392 bytes), down from 49.00GiB (52613349392 bytes) originally
2024-03-17 17:31:05.341431: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 6.94GiB (7451025408 bytes) by rematerialization; only reduced to 49.00GiB (52613349392 bytes), down from 49.00GiB (52613349392 bytes) originally
2024-03-17 17:31:05.411765: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 6.94GiB (7451025408 bytes) by rematerialization; only reduced to 49.00GiB (52613349392 bytes), down from 49.00GiB (52613349392 bytes) originally
2024-03-17 17:31:05.412168: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 6.94GiB (7451025408 bytes) by rematerialization; only reduced to 49.00GiB (52613349392 bytes), down from 49.00GiB (52613349392 bytes) originally
2024-03-17 17:31:05.412362: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 6.94GiB (7451025408 bytes) by rematerialization; only reduced to 49.00GiB (52613349392 bytes), down from 49.00GiB (52613349392 bytes) originally
2024-03-17 17:31:05.412580: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 6.94GiB (7451025408 bytes) by rematerialization; only reduced to 49.00GiB (52613349392 bytes), down from 49.00GiB (52613349392 bytes) originally
2024-03-17 17:31:05.414555: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 6.94GiB (7451025408 bytes) by rematerialization; only reduced to 49.00GiB (52613349392 bytes), down from 49.00GiB (52613349392 bytes) originally
2024-03-17 17:31:05.414553: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 6.94GiB (7451025408 bytes) by rematerialization; only reduced to 49.00GiB (52613349392 bytes), down from 49.00GiB (52613349392 bytes) originally
2024-03-17 17:31:05.416048: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 6.94GiB (7451025408 bytes) by rematerialization; only reduced to 49.00GiB (52613349392 bytes), down from 49.00GiB (52613349392 bytes) originally
2024-03-17 17:31:05.416039: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 6.94GiB (7451025408 bytes) by rematerialization; only reduced to 49.00GiB (52613349392 bytes), down from 49.00GiB (52613349392 bytes) originally
2024-03-17 17:31:05.651736: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 6.94GiB (7451025408 bytes) by rematerialization; only reduced to 49.00GiB (52613349392 bytes), down from 49.00GiB (52613349392 bytes) originally
2024-03-17 17:31:05.652690: W external/xla/xla/service/hlo_rematerialization.cc:2941] Can't reduce memory use below 6.94GiB (7451025408 bytes) by rematerialization; only reduced to 49.00GiB (52613349392 bytes), down from 49.00GiB (52613349392 bytes) originally
2024-03-17 17:31:15.389211: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-17 17:31:15.389451: W external/tsl/tsl/framework/bfc_allocator.cc:494] __**********************************************************************____________________________
E0317 17:31:15.389573 1758840 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-17 17:31:15.391585: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-17 17:31:15.391845: W external/tsl/tsl/framework/bfc_allocator.cc:494] __**********************************************************************____________________________
E0317 17:31:15.391951 1758843 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-17 17:31:15.398355: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-17 17:31:15.398533: W external/tsl/tsl/framework/bfc_allocator.cc:494] __**********************************************************************____________________________
E0317 17:31:15.398605 2464918 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-17 17:31:15.399103: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-17 17:31:15.399210: W external/tsl/tsl/framework/bfc_allocator.cc:494] __**********************************************************************____________________________
E0317 17:31:15.399273 2464917 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-17 17:31:15.411007: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-17 17:31:15.411238: W external/tsl/tsl/framework/bfc_allocator.cc:494] __**********************************************************************____________________________
E0317 17:31:15.411337 2464916 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-17 17:31:15.412155: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-17 17:31:15.412256: W external/tsl/tsl/framework/bfc_allocator.cc:494] __**********************************************************************____________________________
E0317 17:31:15.412339 2464915 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-17 17:31:15.485410: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-17 17:31:15.485616: W external/tsl/tsl/framework/bfc_allocator.cc:494] __**********************************************************************____________________________
E0317 17:31:15.485676 1177074 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-17 17:31:15.487741: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-17 17:31:15.487980: W external/tsl/tsl/framework/bfc_allocator.cc:494] __**********************************************************************____________________________
E0317 17:31:15.488088 1177077 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-17 17:31:15.489385: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-17 17:31:15.489494: W external/tsl/tsl/framework/bfc_allocator.cc:494] __**********************************************************************____________________________
E0317 17:31:15.489559 1177076 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-17 17:31:15.489838: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-17 17:31:15.489943: W external/tsl/tsl/framework/bfc_allocator.cc:494] __**********************************************************************____________________________
E0317 17:31:15.490016 1177075 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-17 17:31:15.501443: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-17 17:31:15.501672: W external/tsl/tsl/framework/bfc_allocator.cc:494] __**********************************************************************____________________________
E0317 17:31:15.501787 2105120 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-17 17:31:15.501971: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-17 17:31:15.502195: W external/tsl/tsl/framework/bfc_allocator.cc:494] __**********************************************************************____________________________
E0317 17:31:15.502298 2105119 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-17 17:31:15.502901: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_3_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-17 17:31:15.503022: W external/tsl/tsl/framework/bfc_allocator.cc:494] __**********************************************************************____________________________
E0317 17:31:15.503096 2105122 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-17 17:31:15.503328: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-17 17:31:15.503438: W external/tsl/tsl/framework/bfc_allocator.cc:494] __**********************************************************************____________________________
E0317 17:31:15.503503 2105121 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-17 17:31:15.718327: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_1_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-17 17:31:15.718549: W external/tsl/tsl/framework/bfc_allocator.cc:494] __**********************************************************************____________________________
E0317 17:31:15.718674 1758841 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


2024-03-17 17:31:15.719814: W external/tsl/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_2_bfc) ran out of memory trying to allocate 16.00GiB (rounded to 17179869440)requested by op 
2024-03-17 17:31:15.720048: W external/tsl/tsl/framework/bfc_allocator.cc:494] __**********************************************************************____________________________
E0317 17:31:15.720154 1758842 pjrt_stream_executor_client.cc:2804] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 110, in <module>
    run_benchmark(global_shape,nb_nodes, output_path)
  File "/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py", line 57, in run_benchmark
    do_fft(global_array).block_until_ready()
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 17179869312 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  512.00MiB
              constant allocation:         0B
        maybe_live_out allocation:   16.00GiB
     preallocated temp allocation:   16.00GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   32.50GiB
              total fragmentation:       128B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 2:
		Size: 16.00GiB
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: fft
		Shape: c128[1024,1024,1024]
		==========================

	Buffer 3:
		Size: 512.00MiB
		Entry Parameter Subshape: f64[64,1024,1024]
		==========================

	Buffer 4:
		Size: 16B
		Operator: op_name="jit(do_fft)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(1024, 1024, 1024)]" source_file="/gpfsdswork/projects/rech/tkc/commun/jaxDecomp/benchmarks/jaxfft.py" source_line=44
		XLA Label: all-gather-start
		Shape: (c128[64,1024,1024], c128[1024,1024,1024])
		==========================


srun: error: r7i5n3: tasks 4,6-7: Exited with exit code 1
srun: Terminating StepId=1125461.26
srun: error: r8i5n6: tasks 12-13,15: Exited with exit code 1
slurmstepd: error: *** STEP 1125461.26 ON r7i2n6 CANCELLED AT 2024-03-17T17:31:16 ***
srun: error: r7i7n3: tasks 8-10: Exited with exit code 1
srun: error: r7i2n6: tasks 0-2: Exited with exit code 1
srun: error: r8i5n6: task 14: Exited with exit code 1
srun: error: r7i5n3: task 5: Exited with exit code 1
srun: error: r7i2n6: task 3: Exited with exit code 1
srun: error: r7i7n3: task 11: Exited with exit code 1
